# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13b2VnSo1n0P6GxTU0x3E_oiJ9fIBT-nA
"""

a=5
b=7
c=6
x=7
y=a*x*x+b*x+c
print(y)