# -*- coding: utf-8 -*-
"""vr1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13b2VnSo1n0P6GxTU0x3E_oiJ9fIBT-nA
"""

a = float(input("Enter the value for a: "))
b = float(input("Enter the value for b: "))
c = float(input("Enter the value for c: "))
x = float(input("Enter the value for x: "))
y = a * x * x + b * x + c
print(y)